### PR TITLE
Various UI fixes after feedback

### LINKED ISSUE #147: Smaller improvements after pre-release feedback
1. Highlight `Import` buttons (the one one Admin panel only if there's no tables yet)
2. Number the steps of import process
3. Try revamping the tab naming (if easy)

See internal discussion for details.

### PR DESCRIPTION
**Pull request by pdobacz**
Closes #147 

The numbered steps:

numbered_steps

The iconned tabs;

tab_with_icons

### CODE REVIEW

File: src/AdminTab/AdminTab.tsx [hunk 1]
```diff
@@ -26,6 +32,11 @@ export const AdminTab: FunctionComponent<AdminTabProps> = ({
   const postgresqlStatus = usePostgresqlStatus();
   const metabaseStatus = useMetabaseStatus();
 
+  const tableListLodable = useTableListLoadable();
+  const tableList = useCachedLoadable(tableListLodable, []);
+  const tableListIsLoading = useIsLoading(tableListLodable);
+  const highlightImport = !tableListIsLoading && tableList.length === 0;
```
Comment (edongashi) [inline src/AdminTab/AdminTab.tsx:38]: `useIsLoading` intentionally delays for 500 milliseconds before saying yes in order to avoid UI flicker. I don't think we want that here. `tableListLodable.state === 'loading'` gives the immediate value.

This whole thing can be simplified to:

```suggestion
  const tableListLodable = useTableListLoadable();
  const highlightImport = tableListLodable.state === 'hasData' && tableListLodable.data.length === 0;
```

File: src/AdminTab/AdminTab.tsx [hunk 2]
```diff
@@ -42,7 +53,12 @@ export const AdminTab: FunctionComponent<AdminTabProps> = ({
         <div className="AdminTab-tables">
           <div className="AdminTab-tables-header">
             <Title level={3}>{t('Imported Tables')}</Title>
-            <Button onClick={onOpenImportDataTab} type="ghost" size="large" icon={<PlusOutlined />}>
+            <Button
+              onClick={onOpenImportDataTab}
+              type={highlightImport ? 'primary' : 'ghost'}
```
Comment (edongashi) [inline src/AdminTab/AdminTab.tsx:58]: It's fine to always have it as `primary`.

File: assets/locales/en/translation.json [hunk 3]
```diff
@@ -68,13 +68,13 @@
   "ImportDataTab": {
     "Sidebar": {
       "ImportDataNavSteps": {
-        "Select File": "Select File",
+        "{{stepNumber}}. Select File": "{{stepNumber}}. Select File",
```
Comment (cristianberneanu) [inline assets/locales/en/translation.json:71]: Passing the step numbers as parameters seems overkill since they are fixed at compile time.

**Review by cristianberneanu — APPROVED** [review]

File: assets/locales/en/translation.json (hunk 3 above)
Comment (pdobacz) [reply assets/locales/en/translation.json:71]: Only reason is to avoid changing the `translation.json` file when adding a new step or something. I started with the numbers verbatim, looked at it and then thought it's going to be a nightmare.

File: src/AdminTab/AdminTab.tsx (hunk 2 above)
Comment (edongashi) [reply src/AdminTab/AdminTab.tsx:58]: On initial import the user will know what the button does. Having it change color suddenly is confusing.

Comment (pdobacz) [reply src/AdminTab/AdminTab.tsx:58]: ok, let's keep it simple

**Review by cristianberneanu — APPROVED** [review]
