### PR TITLE
Prevent breaking syncs on the anonymized access db

### LINKED ISSUE #80: Fix (or prevent, if hard) Metabase automatically analyzing personal tables
It always fails and makes it harder to find any other error in the logs. Worse yet, it clogs the logs and causes unneeded rotation, so useful logs might get lost.

### PR DESCRIPTION
**Pull request by pdobacz**
Closes #80 

Actually, the syncs on cadence were disabled already, but the syncs on refresh were still stumbling upon illegal anonymized queries.

It seems that for Anonymized Access `/sync` instead of `/sync_schema` does the trick (updates the table lists), but doesn't cause illegal queries.

### CODE REVIEW

File: src/main/metabase/api.ts [hunk 1]
```diff
@@ -259,10 +265,13 @@ export async function hasUserSetup(): Promise<boolean> {
...
+  const databases = (await get('/api/database')).data as Array<Database>;
+  const anonymizedAccessDbId = findAnonymizedAccessDbId(databases);
+
   for (const db of databases) {
-    if (!db.is_sample) {
+    if (!db.is_sample && db.id !== anonymizedAccessDbId) {
       await post(`/api/database/${db.id}/sync_schema`, {});
     }
   }
+  await post(`/api/database/${anonymizedAccessDbId}/sync`, {});
```
Comment (edongashi) [inline src/main/metabase/api.ts:276]: It sounds weird that `sync` does only the schema sync and `schema_sync` does the schema sync + analysis...

File: src/main/metabase/api.ts [hunk 2]
```diff
@@ -215,20 +233,8 @@ export async function removeSampleData(): Promise<void> {
...
-  const databaseId = databases.find(
-    (db) => db.details.dbname === postgresConfig.tablesDatabase && db.details.user === postgresConfig.trustedUser,
-  )?.id;
-
-  if (databaseId) {
-    return databaseId;
-  } else {
-    throw new Error('Anonymized access data source not found in Metabase');
-  }
+  const databases = (await get('/api/database')).data as Array<Database>;
```
Comment (edongashi) [inline src/main/metabase/api.ts:236]:
```suggestion
  const databases = (await get('/api/database')).data as Database[];
```

**Review by edongashi — DISMISSED** [review]

**Review by edongashi — APPROVED** [review]
